### ISSUE TITLE
Trying to upload 1Gb firmware file ends in erorr 500

### ISSUE THREAD

**Issue by estreetco** [IBM/dp-file-uploader#2]
I'm trying to upload a large firmware file to the DP appliance.  After about 20-30 min, the program aborts with the following error:

[..]
</dp:set-file>
		</dp:request>
	</env:Body>
</env:Envelope>

Sending POST request
HTTP Response Code: 500
Response XML:

<?xml version="1.0" ?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
	<env:Body>
		<env:Fault>
			<faultcode>env:Client</faultcode>
			<faultstring>Malformed content (from client)</faultstring>
		</env:Fault>
	</env:Body>
</env:Envelope>

Is there a file transfer limit?  The file I am uploading ends with .scrypt3 extension, which is the standard (binary I believe) format of IBM's firmware updates.  This particular file is aprox 970MB in size.

**Comment by aharbis** [comment]
Thanks for reporting this issue! Based on the error, this is likely an error coming directly from the `xml-mgmt` interface, and not caused by the script.

I’ll do some testing to confirm, and see if there’s a workaround.

**Comment by estreetco** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Great, thanks for the update!  Let me know if you want me to test anything else from my end or need further info. I work in a large environment and we have a bunch of new DataPower appliances I am presently setting up. I decided to try your script as it was a bit of a pain setting up routing and trying to get this firmware from other devices (some of which can't even connect). Regards,Jim                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: January 2, 2020 4:51 PMTo: dp-file-uploader@noreply.github.comReply-to: reply@reply.github.comCc: admin@estreetconnection.com; author@noreply.github.comSubject: Re: [IBM/dp-file-uploader] Trying to upload 1Gb firmware file ends in erorr 500 (#2)  Thanks for reporting this issue! Based on the error, this is likely an error coming directly from the xml-mgmt interface, and not caused by the script.

I’ll do some testing to confirm, and see if there’s a workaround.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aharbis** [comment]
@estreetco What firmware version(s) are the target appliance(s) running that saw this issue? I'm still running some tests, but one thing comes to mind is [APAR IT25126](https://www-01.ibm.com/support/docview.wss?uid=swg1IT25126) which increased the internal limits for the SOMA / ROMA interfaces for larger files. This change went into `7.5.2.14` and `7.6.0.7`, so if you are targeting an appliance that's running an older firmware version than that, you may run into problems with large files.

I am currently running some tests against a DataPower running 2018.4.1.9 to confirm.

**Comment by estreetco** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Very interesting and good to know. The devices I was trying to upload it to are brand new 8436-52X, running 7.6.0.2 firmware out of the box. And I was trying to upload the latest firmware (2018.4.x). I didn't try uploading to any other devices, but I do have one appliance running 7.6.0.7 that I also need to upgrade firmware on, so I'll try to upload it to that appliance and will let you know the result. Jim                                                                                                                                                                          From: notifications@github.comSent: January 3, 2020 12:25 PMTo: dp-file-uploader@noreply.github.comReply-to: reply@reply.github.comCc: admin@estreetconnection.com; mention@noreply.github.comSubject: Re: [IBM/dp-file-uploader] Trying to upload 1Gb firmware file ends in erorr 500 (#2)  @estreetco What firmware version(s) are the target appliance(s) running that saw this issue? I'm still running some tests, but one thing comes to mind is APAR IT25126 which increased the internal limits for the SOMA / ROMA interfaces for larger files. This change went into 7.5.2.14 and 7.6.0.7, so if you are targeting an appliance that's running an older firmware version than that, you may run into problems with large files.
I am currently running some tests against a DataPower running 2018.4.1.9 to confirm.

**Comment by aharbis** [comment]
For the appliances you have that are pre APAR IT25126, the following IBM Developer Answers post may be of help:

https://developer.ibm.com/answers/questions/450938/why-datapower-throws-error-document-size-limit-of/

This discusses how you can manually increase the parser limits to allow larger files to be uploaded. Be sure to reset the configuration after upload is complete (steps included in post).

**Comment by estreetco** [comment]
Thanks for the info, I'll check that out.  

So I tried uploading the firmware to an appliance running 7.6.0.7.  This time it got farther, and according to my network monitor there was an active transfer of about 1.8mb/sec for some time.  However, in the end it failed with the following result:

[..] 
</dp:set-file>
            </dp:request>
      </env:Body>
</env:Envelope>
 
Sending POST request
HTTP Response Code: 200
Response XML:
 
<?xml version="1.0" ?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
      <env:Body>
            <dp:response xmlns:dp="http://www.datapower.com/schemas/management">
                  <dp:timestamp>2020-01-03T03:15:51-05:00</dp:timestamp>
                  <dp:result>Authentication failure</dp:result>
            </dp:response>
      </env:Body>
</env:Envelope>
 
File upload failed
Reason: Authentication failure
 
The command line I used is below, and I double checked that the userid and password were correct.  Do you know what might have caused this? Is my syntax correct?
 
dp-file-uploader -u admin -p password1234 device.new image:/// ~/Downloads/idg2018414jf.scrypt3 -V


Jim



  Original Message

**Comment by aharbis** [comment]
Your command looks correct. In my testing today I was also continuously hitting that `Authentication failure` error. The error itself is a bit ambiguous, as of course it's not truly an authentication failure (as the user credentials are valid).

I think it would be worth opening a ticket with the IBM DataPower support team. We've certainly seen this similar behavior before, and usually it's caused by the internal parser limits. However even in my testing today I was unable to get a file upload of ~900 MB to succeed.

If / when you do open the ticket with the support team, feel free to mention my name and this issue, as I'd like to stay engaged on this investigation. Thanks!

**Comment by bibin0dilli** [comment]
Hello

 Did anyone sort this out.. i am getting the same Authentication Error.. i am on latest firmware and i increased xml parser also to a higher value.. please help

**Comment by aharbis** [comment]
@bibin0dilli Please engage [IBM Support](https://www.ibm.com/mysupport) for assistance. The authentication error is indicative of a DataPower issue, not with this `dp-file-uploader` tool. Thanks!
